//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebReservationService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guest
    {
        public int GuestId { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public string Email { get; set; }
        public System.DateTime Data_urodzenia { get; set; }
        public string Adres_pocztowy { get; set; }
        public Nullable<int> Reservation_ReservationId { get; set; }
        public string Telefon { get; set; }
        public string Adres { get; set; }
        public string Miasto { get; set; }
    
        public virtual Reservation Reservation { get; set; }
    }
}
