//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebReservationService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservation()
        {
            this.Guest = new HashSet<Guest>();
        }
    
        public int ReservationId { get; set; }
        public string Kod_Rezerwacji { get; set; }
        public System.DateTime Data_utworzenia { get; set; }
        public int Cena { get; set; }
        public System.DateTime Data_zameldowania { get; set; }
        public System.DateTime Data_wymeldowania { get; set; }
        public string Waluta { get; set; }
        public double Prowizja { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Guest> Guest { get; set; }
    }
}
